package com.deeptalking.core.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
enum class Role {
    @SerialName("system") System,
    @SerialName("user") User,
    @SerialName("assistant") Assistant,
    @SerialName("tool") Tool,
}

/**
 * A conversation message. [content] is plain text; multimodal attachments are
 * carried separately so the transport layer can build the provider payload.
 */
@Serializable
data class ChatMessage(
    val id: String = "",
    val role: Role,
    val content: String = "",
    val timestamp: String? = null,
    val attachments: List<MessageAttachment> = emptyList(),
    val rejected: Boolean = false,
    /** Set on assistant turns that were generated by a proactive (unprompted) round. */
    val internalOnly: Boolean = false,
    /** True while a streamed assistant turn is still being generated. */
    val isLoading: Boolean = false,
    /** Style violations detected on this assistant turn (persisted for the review pass). */
    val styleViolations: List<String> = emptyList(),
    /** Quick-reply issues detected on this assistant turn. */
    val quickReplyIssues: List<String> = emptyList(),
    /** Static profile field labels auto-adjusted after this assistant turn (legacy `staticChanges`). */
    val staticChanges: List<String> = emptyList(),
    /** Lorebook entry names created/updated after this assistant turn (legacy `lorebookChanges`). */
    val lorebookChanges: List<String> = emptyList(),
)

@Serializable
data class MessageAttachment(
    val kind: Kind,
    val uri: String,
    val mimeType: String? = null,
) {
    enum class Kind { Image, Sticker, File }
}
